FROM python:3.8-alpine

RUN apk add --no-cache openssl netcat-openbsd bash

RUN apk add --no-cache --virtual .build-deps build-base libffi-dev openssl-dev \
  && pip3 install flask \
  && pip3 install cryptography \
  && rm -rf /root/.cache \
  && apk del .build-deps

ADD Main /opt/cryptoengine
ADD utils /opt/cryptoengine/utils
ADD docker-entrypoint.sh /opt/cryptoengine/docker-entrypoint.sh
RUN rm /opt/cryptoengine/app/CA_key.pem

ENTRYPOINT ["/opt/cryptoengine/docker-entrypoint.sh"]
CMD [ "python3", "/opt/cryptoengine/run.py" ]
